=== CoWolf/CoWolf/de.uni_stuttgart.iste.cowolf.transformation.model/schema/Mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uni-stuttgart.iste.co.wolf.org/TransformationMapping" xmlns:tns="http://www.uni-stuttgart.iste.co.wolf.org/TransformationMapping" elementFormDefault="qualified">
 <element name="Mappings">
    <complexType>
      <sequence>
        <element maxOccurs="unbounded" name="Mapping">
          <complexType>
            <sequence>
              <element name="Difference" type="string" />
              <element name="Rule">
                <complexType>
                  <sequence>
                    <element name="Params">
                      <complexType>
                        <sequence>
                          <element maxOccurs="unbounded" name="Param">
                            <complexType>
                              <sequence>
                                <element name="Path" type="string" maxOccurs="unbounded" />
                              </sequence>
                              <attribute name="name" type="string" />
                            </complexType>
                          </element>
                        </sequence>
                      </complexType>
                    </element>
                  </sequence>
                  <attribute name="name" type="string" />
                  <attribute name="path" type="string" />
                </complexType>
              </element>
            </sequence>
            <attribute name="priority" type="integer"/>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>
</schema>

=== CoWolf/CoWolf/de.uni_stuttgart.iste.cowolf.transformation.dtmc_statechart.rules/mapping/dtmcmapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<Mappings
	xmlns="http://www.uni-stuttgart.iste.co.wolf.org/TransformationMapping"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uni-stuttgart.iste.co.wolf.org/TransformationMapping Mapping.xsd ">
	<Mapping>
		
		<Difference>CREATE_State_IN_StateMachine_(top)</Difference>
		<Rule name="CreatedStateInSC">
			<Params>
				<Param name="name">
					<Path>AddObject</Path>
					<Path>obj</Path>
					<Path>name</Path>
				</Param>
			</Params>
		</Rule>
	</Mapping>
 	<Mapping>
 		<Difference>DELETE_State_IN_StateMachine_(top)</Difference>
 		<Rule name="DeletedStateInSC">
			<Params>
			</Params>
		</Rule>
 	</Mapping>
	<Mapping>
		<Difference>CREATE_Transition_IN_StateMachine_(transitions)</Difference>
		<Rule name="CreatedTransitionInSC">
			<Params>
				<Param name="name">
					<Path>AddObject</Path>
					<Path>obj</Path>
					<Path>name</Path>
				</Param>
			</Params>
		</Rule>
	</Mapping>
	<Mapping>
		<Difference>DELETE_Transition_IN_StateMachine_(transitions)</Difference>
		<Rule name="DeletedTransitionInSC">
			<Params>
			</Params>
		</Rule>
	</Mapping>
	<Mapping priority="10">
		<Difference>CHANGE_Transition_(target)_TGT_StateVertex</Difference>
		<Rule name="ChangedTransitionTargetInSC">
			<Params>
				<Param name="transName">
					<Path>RemoveReference</Path>
					<Path>target</Path>
					<Path>src</Path>
					<Path>name</Path>
				</Param>
			</Params>
		</Rule>
	</Mapping>
</Mappings>
